### ISSUE TITLE
W polecanych materiałach nie ma żadnego w języku polskim

### ISSUE THREAD

**Issue by banankowy** [SteelPh0enix/KursCPP#2]
> Kurs dla początkującego powinien:
> Być napisany prostym i zrozumiałym językiem. Osoba która nie miała wcześniej styczności z programowaniem nie zrozumie typowo programistycznych terminów

W polecanych materiałach nie ma żadnego w języku polskim

**Comment by SteelPh0enix** [comment]
Nie pisałem nigdzie że materiały powinny być w języku polskim. Ba, powiedziałbym nawet że umiejętność płynnego czytania w języku angielskim jest kluczowa przy dalszych etapach nauki programowania, ponieważ 90% materiałów z których ktoś będzie korzystać będzie po angielsku.
Poza tym, większość książek które poleciłem jest w polskim przekładzie.

**Comment by banankowy** [comment]
Moim zdaniem nie jest to wystarczające wytłumaczenie. Powinieneś polecić także jakiś internetowy kurs.
Początkujący np. gimnazjalista lub właściwie ktoś z podstawówki na pewno nie zna tak dobrze angielskiego.

**Comment by grayrattus** [comment]
Książki Bjarne Stroustrup-a są w polskich tłumaczeniach. Jeżeli ktoś nie zna języka angielskiego na poziomie pozwalającym mu korzystać z kursów zamieszczonych przez @SteelPh0enix  (co w sumie nie jest jakoś mega wymagające) to zostaje mu gruba literatura.
