### ISSUE TITLE
Typo in explanation why 'using namespace' is a root of all evil

### ISSUE THREAD

**Issue by Dzordzu** [SteelPh0enix/KursCPP#3]
In
![obraz](https://user-images.githubusercontent.com/17514622/43012136-dbc1eec6-8c45-11e8-94f4-f0165c2902a5.png)
should be mp instead of mt (the fourth line)

**Comment by SteelPh0enix** [comment]
Fixed on Wiki, but i don't have Markdown to PDF tools installed ATM, so will generate PDF later. Thanks.
